/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'gioba' at '15/11/16 9.34' with Gradle 2.13
 *
 * @author gioba, @date 15/11/16 9.34
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
